export const BASE_URL = "http://localhost:3000";

export const texts = {
  signUp: "ثبت نام",
  signIn: "ورود",
  userName: "نام کاربری",
  password: "رمز عبور",
  email: "ایمیل",
  register: "تایید",
  home: "خانه",
  doctors: "پزشکان",
  blog: "مجله",
  aboutUs: "درباره ما",
  contactUs: "ارتباط با ما",
  specialties: "تخصص ها",
  topDoctors: "پزشکان برتر",
  healthArticle: "مجله سلامت",
  mainPage: "صفحه اصلی",
  links: "پیوند ها",
  services: "خدمات",
  account: "حساب کاربری",
  onlineVisit: "ویزیت آنلاین",
  dashboard: "داشبورد",
  appointments: "نوبت ها",
  patients: "بیماران",
  schedule: "برنامه زمانی",
  medicalSystemCode: "کد نظام پزشکی",
};
